<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PSGraphView.Msagl</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../PSGraph/PSGraph.Common/PSGraph.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutomaticGraphLayout" Version="1.1.12" />
    <PackageReference Include="AutomaticGraphLayout.Drawing" Version="1.1.12" />
  </ItemGroup>

</Project>
