<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PSGraphView.Msagl</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutomaticGraphLayout" Version="1.1.12" />
    <PackageReference Include="AutomaticGraphLayout.Drawing" Version="1.1.12" />
    <PackageReference Include="PSGraph.Common" Version="2.6.0-beta1"
                      Condition="!Exists('../../../PSGraph/PSGraph.Common/PSGraph.Common.csproj')" />
  </ItemGroup>

  <ItemGroup Condition="Exists('../../../PSGraph/PSGraph.Common/PSGraph.Common.csproj')">
    <ProjectReference Include="../../../PSGraph/PSGraph.Common/PSGraph.Common.csproj" />
  </ItemGroup>

</Project>
