<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PSGraphView.Sfdp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PSGraph.Common" Version="2.5.0-beta3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PSGraphView.GVExport/PSGraphView.GVExport.csproj" />
  </ItemGroup>

</Project>
